name: privatepay
version: 0.1.0.0
summary: "PrivatePay: the secure, private, payment ecosystem https://goprivatepay.com"
description: |
    PrivatePay is a secure and private payment ecosystem that allows users to securely send decentralised currency as if it was a fiat currency.
    Allowing end-users to withdraw PrivatePay directly from an ATM machine all around the world. 
    The power to set up Smart Contracts that can be seen as direct debits, Automate these payments to your bill receivers each month.
grade: devel
confinement: strict

apps:
    privatepayd:
        daemon: forking
        command: |
          privatepayd-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/privatepayd.conf
        plugs:
            - network
            - network-bind
    privatepay-wallet-rpc:
        command: |
          privatepay-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    privatepay-wallet-cli:
        command: |
          privatepay-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/privatepayd.conf: etc/privatepayd.conf
            contrib/snap/privatepayd-wrapper: bin/privatepayd-wrapper
        prime:
            - etc
            - bin
